language: swift
xcode_project: SwiftyMarvel.xcodeproj
xcode_scheme: SwiftyMarvelTests
xcode_destination: platform=iOS Simulator,OS=16.4,name=iPhone 14
before_install:
  - rvm implode --force
  - \curl -sSL https://get.rvm.io | bash -s 1.27.0
  - rvm reload
  - rvm install 2.6.9