language: swift
osx_image: xcode14.2
xcode_project: SwiftyMarvel.xcodeproj
xcode_scheme: SwiftyMarvelTests
xcode_destination: platform=iOS Simulator,OS=16.2,name=iPhone 14
before_install:
  - rvm install 2.6.9
  - rvm use 2.6.9
  - touch .env
  - echo "MarvelPublicKey=$MarvelPublicKey" >> .env
  - echo "MarvelPrivateKey=$MarvelPrivateKey" >> .env
install:
  - gem install buildr
  - gem install bundler
  - bundle install
  - bundle binstubs arkana
  - bin/arkana
script:
  - xcodebuild clean build test -project SwiftyMarvel.xcodeproj -scheme SwiftyMarvel -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet