language: swift
osx_image: xcode14.2
xcode_project: SwiftyMarvel.xcodeproj
xcode_scheme: SwiftyMarvelTests
xcode_destination: platform=iOS Simulator,OS=16.2,name=iPhone 14
before_install:
  - rvm install 2.6.9
  - rvm use 2.6.9
  - touch .env
  - echo "MarvelPublicKey=$MarvelPublicKey" >> .env
  - echo "MarvelPrivateKey=$MarvelPrivateKey" >> .env
install:
  - gem install buildr
  - gem install bundler
  - gem install xcpretty
  - bundle install
  - bundle binstubs arkana
  - bin/arkana
script:
  - travis_wait xcodebuild clean build test -project SwiftyMarvel.xcodeproj -scheme SwiftyMarvel -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -verbose | xcpretty
after_success:
  - slather coverage -s --scheme SwiftyMarvelTests SwiftyMarvel.xcodeproj
  - bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml -X coveragepy -X gcov -X xcode