name: Run Tests and Upload code coverage to Codecov
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Add .env file
        run: |
          touch .env
          echo "MarvelPublicKey=$MarvelPublicKey" >> .env
          echo "MarvelPrivateKey=$MarvelPrivateKey" >> .env
      - name: Install Bundler
        run: gem install bundler
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Install Gems
        run: |
          bundle install
          bundle binstubs arkana
          bin/arkana
      - name: Build & Test
        run: xcodebuild clean build test -project SwiftyMarvel.xcodeproj -scheme SwiftyMarvel -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -verbose | xcpretty
      - name: Prepare code coverage report
        run: slather coverage -s --scheme SwiftyMarvel SwiftyMarvel.xcodeproj
      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cobertura.xml
          fail_ci_if_error: true
          verbose: true
